#!/bin/bash
# This is a hardcoded variable <-- should be moved
aws --profile ins-dev sqs get-queue-attributes --queue-url https://sqs.ap-southeast-1.amazonaws.com/182387550209/invites --attribute-names ApproximateNumberOfMessages
# This is a hardcoded variable