#!/bin/bash
# This is a hardcoded variable <-- should be moved
aws --profile ins-dev sqs receive-message --queue-url https://sqs.ap-southeast-1.amazonaws.com/182387550209/invites
# END This is a hardcoded variable